name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: false  # Cache disable kora holo jate 422 error na dey

      - name: Install dependencies
        run: npm install

      - name: Run app (optional)
        run: npm start

      - name: Run tests (if any)
        run: npm test
